import { Chip, Divider, Grid, Link, Paper, Typography, Box } from '@mui/material'
import { Container } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Chooser } from '../components/Chooser'
import { Schedule } from '../components/Schedule/Schedule'
import { Title } from '../components/Title/Title'
import { ZachIsDumb } from '../components/ZachIsDumb/ZachIsDumb'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LD-BDAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ width: '100%',  margin: 0, minHeight: '100vh'}}>
        {/* <Image width={50}
          height={50}
          src='/lk.jpg'
          alt='l k'
        /> */}
        <Title/>
        <ZachIsDumb />
        <Divider/>

        <Schedule/>
        
        <Paper sx={{textAlign: 'center'}}>
          <Chooser />
        </Paper>
        <Box sx={{height: '20px'}}/>
      </Container>
    </>

  )
}

export default Home
