import { Grid, Link, Paper, Typography } from '@mui/material'
import { Container } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LK BDAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ width: '100%'}} color='white'>
          <Typography variant='h1' align={'center'}>
            LK BDAY
          </Typography>
        
        <Paper>
          <Typography variant='h3' >
            Schedule:
          </Typography>
        </Paper>
        
        <Paper>
          <Typography variant='h3' >
            Chooser:
          </Typography>
        </Paper>
        
      </Container>
    </>

  )
}

export default Home
