import { Chip, Divider, Grid, Link, Paper, Typography } from '@mui/material'
import { Container } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Schedule } from '../components/Schedule/Schedule'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LK BDAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ width: '100%'}} color='white'>
        <Paper sx={{ padding: 0, width: '80%', hieght: 'min-content', borderRadius: '26px', overflow: 'hidden', margin: 'auto' }} >
          <Grid container>
            <Grid item>
              <Image width={500}
                height={500}
                src='/lk.jpg'
                alt='l k'
              />
            </Grid>
          </Grid>
        </Paper>
          <Typography variant='h1' align={'center'}>
            LK BDAY
          </Typography>
      

          <Divider/>
        
        <Schedule/>
        
        <Paper>
          <Chooser />
        </Paper>

      </Container>
    </>

  )
}

export default Home
